#!/bin/bash

# Check if node_modules exists, if not install dependencies
if [ ! -d "node_modules" ]; then
    echo "Installing dependencies..."
    pnpm install
fi

if [ ! -f "bundle.mjs" ]; then
    echo "Bundling..."
    pnpm build
fi

# Run the Node.js server
node bundle.mjs